@RoverCommandService_HostAddress = https://localhost:7015

POST {{RoverCommandService_HostAddress}}/commandrover/
Content-Type: application/json
Connection: keep-alive
Accept: application/json

{
    "commands": "blffffff"
}

###
